name: CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    uses: knyghty/actions/.github/workflows/lint-python.yml@main
    with:
      black: true
      flake8: true
      isort: true
      mypy: true
      package-manager: pipenv
      python-version: "3.10"
